version: '3.7'

services:
  frontend:
    mem_limit: 128m
    cpus: 0.1

    restart: unless-stopped
    image: stefanlaux/223-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8009:80
  backend:
    mem_limit: 512M
    cpus: 0.2

    restart: unless-stopped
    image: stefanlaux/223-backend
    container_name: backend
    ports:
      - 8080
    depends_on:
      - db
  db:
    mem_limit: 128m
    cpus: 0.05

    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
