name: Pipeline Testing
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        working-directory: "./backend"
        run: ./gradlew build
        with:
          java-version: '18'

      - name: Test backend
        working-directory: "./backend"
        run: ./gradlew test
        with:
          java-version: '18'