name: Pipeline Testing
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Build backend
        working-directory: "./backend"
        with:
          java-version: '18'
        run: ./gradlew build

      - name: Test backend
        working-directory: "./backend"
        with:
          java-version: '18'
        run: ./gradlew test
