name: Pipeline Testing
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        run: ./backend/gradlew build

      - name: Test backend
        run: ./backend/gradlew test