name: backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test backend
        uses: docker://gradle:6.9.2-jdk11
        working-directory: ./backend
        with:
          entrypoint: sh
          args:
            - -c
            - |
              gradle build
              gradle test
