name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Frontend Docker image
      run: docker build --tag 223-frontend ./frontend
    - name: Build the Backend Docker image
      run: docker build --tag 223-backend ./backend
