name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello with Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Hello World! My secret is $MY_SECRET"